apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hk85pvoyt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hk85pvoyt-nodejs 
  name: hk85pvoyt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hk85pvoyt-nodejs 
